/**
 * Analytics export — builds the HTML for the PDF (expo-print) and a canvas page
 * for the PNG (rendered in an off-screen WebView so it works in Expo Go, where
 * native view-shot isn't available). Both describe the same summary.
 */
import { formatINR } from './format';

export interface AnalyticsExport {
  shopName: string;
  periodLabel: string;
  netPnl: number;
  sales: number;
  credit: number;
  inventory: number;
  topStaff: string;
  best: { name: string; units: number; revenue: number }[];
}

/** Professional analytics summary HTML for the PDF. */
export function analyticsHtml(p: AnalyticsExport): string {
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const kpi = (label: string, value: string) =>
    `<div class="kpi"><div class="kl">${label}</div><div class="kv">${value}</div></div>`;
  const best = p.best
    .map((b, i) => `<tr><td>${i + 1}. ${esc(b.name)}</td><td>${b.units} units</td><td>${formatINR(b.revenue)}</td></tr>`)
    .join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; color: #0F1222; padding: 28px; }
    .h { font-size: 22px; font-weight: 800; }
    .sub { font-size: 13px; color: #6B7280; margin-top: 2px; }
    .hero { margin-top: 18px; padding: 20px; border-radius: 16px; background: #EDF2FD; }
    .hl { font-size: 13px; color: #2563EB; font-weight: 700; }
    .hv { font-size: 34px; font-weight: 800; letter-spacing: -1px; margin-top: 4px; }
    .grid { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 16px; }
    .kpi { flex: 1 1 44%; border: 1px solid #E7E9F2; border-radius: 12px; padding: 14px; }
    .kl { font-size: 12px; color: #6B7280; } .kv { font-size: 18px; font-weight: 800; margin-top: 4px; }
    h3 { margin: 22px 0 8px; font-size: 15px; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 8px 0; border-bottom: 1px solid #F2F3F7; font-size: 13px; }
    td:last-child { text-align: right; font-weight: 700; }
    .foot { text-align: center; color: #9AA0AC; font-size: 11px; margin-top: 26px; }
  </style></head><body>
    <div class="h">${esc(p.shopName)}</div>
    <div class="sub">Analytics summary · ${esc(p.periodLabel)}</div>
    <div class="hero"><div class="hl">Net Profit &amp; Loss</div><div class="hv">${formatINR(p.netPnl)}</div></div>
    <div class="grid">
      ${kpi('Total Sales', formatINR(p.sales))}
      ${kpi('Credit Outstanding', formatINR(p.credit))}
      ${kpi('Inventory Value', formatINR(p.inventory))}
      ${kpi('Top Staff', esc(p.topStaff || '—'))}
    </div>
    ${p.best.length ? `<h3>Best-selling items</h3><table>${best}</table>` : ''}
    <div class="foot">Generated by Claro</div>
  </body></html>`;
}

/** A self-contained canvas page that draws the summary and posts a PNG data URL. */
export function analyticsCanvasHtml(p: AnalyticsExport): string {
  const data = JSON.stringify(p).replace(/</g, '\\u003c');
  return `<!DOCTYPE html><html><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /></head>
  <body style="margin:0">
  <canvas id="c" width="720" height="900"></canvas>
  <script>
    var P = ${data};
    function inr(n){ n = Math.round(Math.abs(n)); var s = String(n); if (s.length <= 3) return '\\u20B9'+s;
      var l3 = s.slice(-3), rest = s.slice(0,-3).replace(/\\B(?=(\\d{2})+(?!\\d))/g, ','); return '\\u20B9'+rest+','+l3; }
    var dpr = 2, W = 720, H = 900;
    var c = document.getElementById('c'); c.width = W*dpr; c.height = H*dpr;
    var x = c.getContext('2d'); x.scale(dpr, dpr);
    function rr(px,py,w,h,r){ x.beginPath(); x.moveTo(px+r,py); x.arcTo(px+w,py,px+w,py+h,r);
      x.arcTo(px+w,py+h,px,py+h,r); x.arcTo(px,py+h,px,py,r); x.arcTo(px,py,px+w,py,r); x.closePath(); }
    x.fillStyle = '#FFFFFF'; x.fillRect(0,0,W,H);
    x.fillStyle = '#0F1222'; x.font = '800 30px sans-serif'; x.fillText(P.shopName, 40, 64);
    x.fillStyle = '#6B7280'; x.font = '500 16px sans-serif'; x.fillText('Analytics summary \\u00B7 ' + P.periodLabel, 40, 92);
    x.fillStyle = '#EDF2FD'; rr(40,120,640,140,18); x.fill();
    x.fillStyle = '#2563EB'; x.font = '700 16px sans-serif'; x.fillText('Net Profit & Loss', 64, 162);
    x.fillStyle = '#0F1222'; x.font = '800 46px sans-serif'; x.fillText(inr(P.netPnl), 64, 222);
    var kpis = [['Total Sales', inr(P.sales)],['Credit Outstanding', inr(P.credit)],['Inventory Value', inr(P.inventory)],['Top Staff', P.topStaff || '—']];
    for (var i=0;i<kpis.length;i++){ var col=i%2, row=(i/2)|0; var kx=40+col*330, ky=290+row*120;
      x.strokeStyle='#E7E9F2'; x.lineWidth=1.5; rr(kx,ky,310,100,14); x.stroke();
      x.fillStyle='#6B7280'; x.font='500 15px sans-serif'; x.fillText(kpis[i][0], kx+20, ky+38);
      x.fillStyle='#0F1222'; x.font='800 24px sans-serif'; x.fillText(kpis[i][1], kx+20, ky+74); }
    var by = 560; x.fillStyle='#0F1222'; x.font='800 18px sans-serif'; x.fillText('Best-selling items', 40, by);
    by += 28; var best = P.best || [];
    for (var j=0;j<best.length && j<5;j++){ x.fillStyle='#0F1222'; x.font='700 16px sans-serif';
      x.fillText((j+1)+'. '+best[j].name, 40, by); x.fillStyle='#6B7280'; x.font='500 14px sans-serif';
      x.textAlign='right'; x.fillText(inr(best[j].revenue), 680, by); x.textAlign='left'; by += 38; }
    x.fillStyle='#9AA0AC'; x.font='500 13px sans-serif'; x.textAlign='center'; x.fillText('Generated by Claro', W/2, 860); x.textAlign='left';
    var url = c.toDataURL('image/png');
    function post(){ if (window.ReactNativeWebView) window.ReactNativeWebView.postMessage(url); }
    post();
  </script></body></html>`;
}
